### ISSUE TITLE
Is registry.demo.marklogic.com down?

### ISSUE THREAD

**Issue by peetkes** [joemfb/mlpm#18]
For some reason mlpm is not working anymore. Is the registry.demo.marklogic.com server down?
This is the error:
````
mlpm search XML
 message=Unexpected token < in JSON at position 0, stack=SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/mlpm/lib/api.js:30:27)
    at Request.self.callback (/usr/local/lib/node_modules/mlpm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/mlpm/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/mlpm/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
````

**Comment by grtjn** [comment]
Back up..

**Comment by grtjn** [comment]
Mental note, I need to add an init script..
